# Generated by Django 4.0.3 on 2022-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_alter_item_date_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
