# Generated by Django 4.0.3 on 2022-03-28 17:21

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images2',
            fields=[
                ('First_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('Patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_id', models.IntegerField()),
                ('category', models.CharField(max_length=400)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=images.models.user_directory_path)),
                ('image_date', models.CharField(max_length=250)),
            ],
        ),
    ]
