# Generated by Django 4.0.3 on 2022-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='Image_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='pa_id',
            field=models.TextField(default=1828287271),
            preserve_default=False,
        ),
    ]
