# Generated by Django 4.0.3 on 2022-03-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_item_id_item_image_id_item_pa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Image_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pa_id',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
