# Generated by Django 4.0.3 on 2022-03-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_remove_item_id_item_image_id_item_pa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Idate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Image_id',
            new_name='Imageid',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='pa_id',
            new_name='patientid',
        ),
    ]
