# Generated by Django 4.0.3 on 2022-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_item_id_alter_item_imageid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='imageid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
