# Generated by Django 4.0.3 on 2022-07-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_remove_item_id_alter_item_imageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=191)),
                ('docid', models.TextField(max_length=50)),
            ],
        ),
    ]
