# Generated by Django 4.0.3 on 2022-07-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_roommember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Date',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
